openapi: 3.2.0
info:
  version: v2
  title: Lemonway DirectKit API 2.0 MoneyIns | Direct Debits API
servers:
- url: https://ws.lemonway.fr/mb/env-name/prod/directkitrest/
tags:
- name: MoneyIns | Direct Debits
paths:
  /v2/moneyins/sdd:
    get:
      tags:
      - MoneyIns | Direct Debits
      summary: List of Money-In by SEPA Direct Debit (SDD)
      description: Returns the list of Money-In by SDD which status has changed since the input date.
      operationId: MoneyIns_SddGet
      parameters:
      - name: reference
        in: query
        description: Unique ID Generated by your Server
        required: false
        schema:
          type: string
          minLength: 0
          maxLength: 50
      - name: updateDate
        in: query
        description: UTC Unix Timestamp
        required: false
        schema:
          type: string
          pattern: ^-?\d{1,12}$
      - name: updateEndDate
        in: query
        description: End Date UTC Unix Timestamp
        required: false
        schema:
          type: string
          pattern: ^-?\d{1,12}$
      - name: page
        in: query
        description: Index start from 1, let null to get all
        required: false
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: Default 20, let it null if no pagination
        required: false
        schema:
          type: integer
          format: int32
      - name: Authorization
        in: header
        description: Authorization bearer (OAuth 2)
        required: true
        schema:
          type: string
      - name: PSU-Accept-Language
        in: header
        description: Response language accepted by final client (PSU). English by default
        required: false
        schema:
          type: string
      - name: PSU-IP-Address
        in: header
        description: IP address of the final client (PSU).
        required: true
        schema:
          type: string
      - name: PSU-User-Agent
        in: header
        description: User-agent of the final client (PSU).
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMoneyInSddOutput'
              examples:
                response:
                  value:
                    transactions:
                      value:
                      - receiverAccountId: pizza
                        creditAmount: 1500
                        scheduledNumber: null
                        refundAmount: 1500
                        bankReference: null
                        ChequeSendingAddress_CorporateName: null
                        ChequeSendingAddress_Street: null
                        ChequeSendingAddress_City: null
                        ChequeSendingAddress_PostCode: null
                        id: 255
                        method: 0
                        date: 1784563474
                        commissionAmount: 100
                        comment: '245'
                        status: 0
                        executionDate: 0
                        reference: null
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
  /v2/moneyins/sdd/init:
    post:
      tags:
      - MoneyIns | Direct Debits
      summary: Request a SEPA Direct Debit (SDD)
      description: 'SEPA Direct Debit requests are sent to our bank every working day at 10:30am (CET).


        Prequisites:


        1. You allow your client to fill in a mandate, and pre-registers it with Lemonway, by calling POST /moneyins/sdd/mandate


        2. Follow the SignDocumentInit process in order to electronically sign the mandate


        Request the direct debit:


        1. You call POST /moneyins/sdd/init to request a debit


        2. Lemonway sends the request to the bank every working day at 10:30am (CET).


        3. Once the request is sent to the bank, the debit on the customer''s bank account will happens about 1 working day later. If you indicate a date, the debit will happen on the given date.


        4. When Lemonway receives the payment, the SDD payment will be validated and the client payment account will be credited


        5. You can call GET /moneyins/sdd once a day in order to know which payments have been validated.You can also use our notification functionality.


        **Important: Setting up an SDD with Italian Banks**. This rule **only applies to the first** B2B direct debit request for an Italian IBAN.

        Thereafter, **all future debits** take place within the **standard 1-2 day** time frame. The mandate validation process for Italian banks

        takes approximately 14 calendar days from the reception of the first SDD request. Even if you initially specify a debit date, the funds

        will only be debited 14 days after the request date.

        **Example:** If you specify that you would like the first Direct Debit to take place on 4th April 2022 and you submit a request before 10:30am (CET)

        on the 30th March 2022. The direct debit will take place on 18th April 2022.'
      operationId: MoneyIns_SddInitPost
      parameters:
      - name: Authorization
        in: header
        description: Authorization bearer (OAuth 2)
        required: true
        schema:
          type: string
      - name: PSU-Accept-Language
        in: header
        description: Response language accepted by final client (PSU). English by default
        required: false
        schema:
          type: string
      - name: PSU-IP-Address
        in: header
        description: IP address of the final client (PSU).
        required: true
        schema:
          type: string
      - name: PSU-User-Agent
        in: header
        description: User-agent of the final client (PSU).
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoneyInSddInitInput'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoneyInSddInitOutput'
              examples:
                response:
                  value:
                    transaction:
                      receiverAccountId: Pizza56
                      creditAmount: 1500
                      scheduledNumber: null
                      refundAmount: 0
                      bankReference: null
                      ChequeSendingAddress_CorporateName: null
                      ChequeSendingAddress_Street: null
                      ChequeSendingAddress_City: null
                      ChequeSendingAddress_PostCode: null
                      id: 677
                      method: 0
                      date: 1784563474
                      commissionAmount: 200
                      comment: '245'
                      status: 0
                      executionDate: 0
                      reference: Dze8778
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
  /v2/moneyins/sdd/mandate:
    post:
      tags:
      - MoneyIns | Direct Debits
      summary: Register a SDD Mandate
      description: ''
      operationId: MoneyIns_SddMandatePost
      parameters:
      - name: Authorization
        in: header
        description: Authorization bearer (OAuth 2)
        required: true
        schema:
          type: string
      - name: PSU-Accept-Language
        in: header
        description: Response language accepted by final client (PSU). English by default
        required: false
        schema:
          type: string
      - name: PSU-IP-Address
        in: header
        description: IP address of the final client (PSU).
        required: true
        schema:
          type: string
      - name: PSU-User-Agent
        in: header
        description: User-agent of the final client (PSU).
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterSddMandateInput'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterSddMandateOutput'
              examples:
                response:
                  value:
                    SSDMandate:
                      id: 253
                      status: 0
                      UniqueMandateReference: XXXXXXXXX
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
  /v2/moneyins/sdd/mandate/{mandatid}/unregister:
    put:
      tags:
      - MoneyIns | Direct Debits
      summary: Deactivate a Mandate
      description: This allows you to deactivate a mandate
      operationId: MoneyIns_SddMandateUnregisterPut
      parameters:
      - name: mandatid
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: Authorization
        in: header
        description: Authorization bearer (OAuth 2)
        required: true
        schema:
          type: string
      - name: PSU-Accept-Language
        in: header
        description: Response language accepted by final client (PSU). English by default
        required: false
        schema:
          type: string
      - name: PSU-IP-Address
        in: header
        description: IP address of the final client (PSU).
        required: true
        schema:
          type: string
      - name: PSU-User-Agent
        in: header
        description: User-agent of the final client (PSU).
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnregisterSddMandateInput'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnregisterSddMandateOutput'
              examples:
                response:
                  value:
                    SDDMandate:
                      id: 255
                      status: 8
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
  /v2/moneyins/{accountid}/mandate:
    get:
      tags:
      - MoneyIns | Direct Debits
      summary: Get Mandate Associated to a Payment Account
      operationId: MoneyIns_MandateGet
      parameters:
      - name: accountid
        in: path
        description: Account ID
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: Authorization bearer (OAuth 2)
        required: true
        schema:
          type: string
      - name: PSU-Accept-Language
        in: header
        description: Response language accepted by final client (PSU). English by default
        required: false
        schema:
          type: string
      - name: PSU-IP-Address
        in: header
        description: IP address of the final client (PSU).
        required: true
        schema:
          type: string
      - name: PSU-User-Agent
        in: header
        description: User-agent of the final client (PSU).
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountMandatsOutput'
              examples:
                response:
                  value:
                    mandates:
                    - id: 98
                      status: 5
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
  /v2/moneyins/{accountid}/mandate/{mandateid}/document:
    get:
      tags:
      - MoneyIns | Direct Debits
      summary: Get Mandate Document
      description: Download a mandate document that is registered to one of your payment accounts.
      operationId: MoneyIns_MandateGetDocument
      parameters:
      - name: accountid
        in: path
        description: Account Id
        required: true
        schema:
          type: string
      - name: mandateid
        in: path
        description: Id of the registered SDD Mandate
        required: true
        schema:
          type: integer
          format: int64
      - name: Authorization
        in: header
        description: Authorization bearer (OAuth 2)
        required: true
        schema:
          type: string
      - name: PSU-Accept-Language
        in: header
        description: Response language accepted by final client (PSU). English by default
        required: false
        schema:
          type: string
      - name: PSU-IP-Address
        in: header
        description: IP address of the final client (PSU).
        required: true
        schema:
          type: string
      - name: PSU-User-Agent
        in: header
        description: User-agent of the final client (PSU).
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MandateGetDocumentOutput'
              examples:
                response:
                  value:
                    document: RXhlbXBsZSBwZGYgYmFzZTY0Cg==...
                    name: mandate.pdf
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
  /v2/moneyins/{transactionid}/cancel:
    put:
      tags:
      - MoneyIns | Direct Debits
      summary: Cancel a Money-In
      description: With the PUT /moneyins/{transactionid}/cancel method, you can cancel a pre-authorization / SEPA Direct Debit (SDD) request.
      operationId: MoneyIns_CancelPut
      parameters:
      - name: transactionid
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: Authorization
        in: header
        description: Authorization bearer (OAuth 2)
        required: true
        schema:
          type: string
      - name: PSU-Accept-Language
        in: header
        description: Response language accepted by final client (PSU). English by default
        required: false
        schema:
          type: string
      - name: PSU-IP-Address
        in: header
        description: IP address of the final client (PSU).
        required: true
        schema:
          type: string
      - name: PSU-User-Agent
        in: header
        description: User-agent of the final client (PSU).
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelMoneyInInput'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelMoneyInOutput'
              examples:
                response:
                  value:
                    transaction:
                      receiverAccountId: pizza
                      creditAmount: 1500
                      scheduledNumber: null
                      card:
                        id: 0
                        is3DS: true
                        country: FRA
                        authorizationNumber: '4564'
                        maskedNumber: 4972XXXXXXXXXX03
                        type: VISA
                        isRegistered: false
                        holderName: Peter PAN
                      refundAmount: 0
                      bankReference: null
                      ChequeSendingAddress_CorporateName: null
                      ChequeSendingAddress_Street: null
                      ChequeSendingAddress_City: null
                      ChequeSendingAddress_PostCode: null
                      id: 255
                      method: 0
                      date: 1784563474
                      commissionAmount: 200
                      comment: order 245
                      status: 0
                      executionDate: 0
                      reference: null
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
components:
  schemas:
    TransactionIn:
      type: object
      properties:
        receiverAccountId:
          description: Credited Account
          type: string
        creditAmount:
          format: int32
          description: 'Credited Amount

            Amounts represented in integer (cents)'
          type: integer
        scheduledDate:
          description: ''
          type: string
        scheduledNumber:
          description: ''
          type: string
        maskedLabel:
          type: string
        PSP:
          $ref: '#/components/schemas/PSP'
        card:
          $ref: '#/components/schemas/Card'
        bankStatus:
          type: string
        refundAmount:
          format: double
          type: number
        bankReference:
          description: Bank reference
          type: string
        ChequeSendingAddress_CorporateName:
          description: A specified postal address for the cheque
          type: string
        ChequeSendingAddress_Street:
          description: Cheque sending address street name
          type: string
        ChequeSendingAddress_City:
          description: Cheque sending address city name
          type: string
        ChequeSendingAddress_PostCode:
          description: Cheque sending address post code
          type: string
        threeDS:
          $ref: '#/components/schemas/ThreeDs'
        buyNowPayLaterInfo:
          $ref: '#/components/schemas/BnplInfo'
        id:
          format: int64
          description: Transaction ID
          type: integer
        method:
          format: int32
          description: "Payment Method  \n0 Card    \n1 Bank transfer (MoneyIn)     \n3 Bank transfer (MoneyOut)     \n4 P2P    \n13 iDEAL    \n14 SEPA DirectDebit    \n15 Cheque    \n19 Multibanco    \n21 MBWAY    \n30 BNPL  \n35 PayPal\n\n ---\n **Important:** The following services have been discontinued. \n \n16 Neosurf  \n17 Sofort  \n18 PFS Physical Card  \n20 Payshop  \n22 Polish Instant Transfer  \n23 Pagare  \n24 MobilePay\n25 Paytrail\n26 WeChat  \n27 P24  \n28 MoneyIn by TPE  \n29 Trustly"
          type: integer
        methodDetails:
          format: int32
          description: 'Payment Method Details

            0 Standard

            1 Pay By Bank<br/>0 = STANDARD.<br/>1 = PAY_BY_BANK.<br/>'
          enum:
          - 0
          - 1
          type: integer
        date:
          format: int32
          description: Transaction initialization date, UTC Unix timestamp
          type: integer
        commissionAmount:
          format: int32
          description: 'Your fee

            Amounts are given as integer numbers in cents'
          type: integer
        comment:
          description: Comment
          type: string
        status:
          format: int32
          description: "**For the following endpoints uses the below status code**   \n  \n/v2/accounts/{accountId}/transactions\n/v2/moneyins\n/v2/moneyins/card/direct\n/v2/moneyins/card/{cardid}/rebill\n/v2/moneyins/card/{cardid}/subscription\n/v2/moneyins/{transactionid}/validate\n/v2/moneyins/sdd/init\n/v2/moneyins/sdd\n/v2/moneyins/{transactionid}/cancel\n/v2/refund/{transactionid}\n/v2/refundcreate/{transactionId}\n            \n0: Success  \n3: Lemonway Error  \n4: Pending  \n6: PSP error  \n7: Cancelled  \n16: Validation pending  \n\n**For the following endpoints uses the below status code**  \n\n/v2/disputes\n/v2/moneyins/bankwire\n/v2/moneyins/card/direct/3dinit\n/v2/moneyouts\n/v2/p2p\n/v2/p2p/{transactionid?}\n            \n0: Waiting for finalization    \n3: Success    \n4: Lemonway Error"
          type: integer
        executionDate:
          format: int32
          description: Transaction execution date
          type: integer
        lemonWayCommission:
          $ref: '#/components/schemas/LemonWayCommission'
        reference:
          description: Unique ID generated by your server
          type: string
        remainingAmount:
          format: int32
          type: integer
        substatus:
          description: Is Payment token consumed?
          type: string
    Error:
      type: object
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        psp:
          $ref: '#/components/schemas/PSP'
    BnplInfo:
      type: object
      properties:
        paymentPlanId:
          format: int64
          description: Payment Plan ID
          type: integer
        type:
          description: Payment plan type.
          type: string
        secondInstallmentPaymentDate:
          description: 'Second installment payment date.

            Format: yyyy-MM-dd'
          type: string
        deferredPaymentDate:
          description: 'Deferred payment date.

            Format: yyyy-MM-dd'
          type: string
    Link:
      type: object
      properties:
        href:
          type: string
        templated:
          type: boolean
          readOnly: true
        method:
          type: string
        type:
          type: string
        deprecation:
          type: string
        name:
          type: string
        profile:
          type: string
        title:
          type: string
        hreflang:
          type: string
    MoneyInSddInitOutput:
      type: object
      properties:
        transaction:
          $ref: '#/components/schemas/TransactionIn'
        error:
          $ref: '#/components/schemas/Error'
    Transactions_TransactionIn:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: '#/components/schemas/TransactionIn'
    CancelMoneyInOutput:
      type: object
      properties:
        transaction:
          $ref: '#/components/schemas/TransactionIn'
        error:
          $ref: '#/components/schemas/Error'
    UnregisterSddMandateInput:
      required:
      - account
      type: object
      properties:
        account:
          description: Payment Account ID
          maxLength: 256
          minLength: 0
          type: string
      example:
        account: '33612345678'
    LemonWayCommission:
      type: object
      properties:
        idp2p:
          type: string
        amount:
          format: int32
          description: 'Amounts are represented as integer in cents (Euro)

            Represented as an integer in cents (Euro)'
          type: integer
    UnregisterSddMandateOutput:
      type: object
      properties:
        SDDMandate:
          $ref: '#/components/schemas/SddMandate'
        error:
          $ref: '#/components/schemas/Error'
    ThreeDs:
      type: object
      properties:
        threeDSModeRequested:
          description: "3DS Exemption Request  \nPossible value:  \n\nNO_PREFERENCE: The issuing Bank can choose to activate or not 3DS v2."
          type: string
        threeDSResult:
          description: "3DS Authentication Result  \nPossible values:  \n\n- CHALLENGE: 3DS v2 was activated and the card owner was asked to be strongly authenticated.  \n- FRICTIONLESS: 3DS v2 was not activated.  \n- NONE: We could not get the SCA result."
          type: string
    RegisterSddMandateInput:
      required:
      - wallet
      - holder
      - bic
      - iban
      - isRecurring
      type: object
      properties:
        wallet:
          description: Payment Account ID
          maxLength: 256
          minLength: 0
          type: string
        holder:
          description: Debtor Name
          maxLength: 100
          minLength: 0
          type: string
        bic:
          description: BIC Code (SWIFT)
          maxLength: 11
          minLength: 0
          type: string
        iban:
          description: IBAN
          maxLength: 34
          minLength: 15
          type: string
        isB2B:
          description: Indicates if the mandate is a SEPA business to business direct debit
          type: boolean
        isRecurring:
          description: '1. If true, mandate is for recurring payments

            2. If false, mandate is for one payment only'
          type: boolean
        street:
          description: 'Client Number and Street

            Mandatory if you plan to electronically sign the mandate'
          maxLength: 256
          minLength: 0
          type: string
        postCode:
          description: 'Client Postal Code/ZIP

            Mandatory if you plan to electronically sign the mandate'
          maxLength: 10
          minLength: 0
          type: string
        city:
          description: 'Client City

            Mandatory if you plan to electronically sign the mandate'
          maxLength: 256
          minLength: 0
          type: string
        country:
          description: 'Client Country

            Mandatory if you plan to electronically sign the mandate.'
          maxLength: 256
          minLength: 0
          type: string
        mandateLanguage:
          description: "Language of the automatically generated mandate(for electronic signature).\nCurrently, the available languages are: fr, en, de, es, it.\nIf you need another, please contact us. \n\"fr\" is used by default if no language is requested."
          maxLength: 2
          minLength: 2
          type: string
        rum:
          description: Unique Mandate Reference Number (UMR)
          type: string
        signerFirstName:
          description: 'Signer''s First Name

            Required when `SignerLastName` is provided.'
          maxLength: 256
          minLength: 0
          type: string
        signerLastName:
          description: 'Signer''s Last Name.

            Required when `SignerFirstName` is provided.'
          maxLength: 256
          minLength: 0
          type: string
      example:
        wallet: '33612345678'
        holder: Jean Dupont
        bic: ABCDEFGHIJK
        iban: FR1420041010050500013M02606
        isB2B: true
        isRecurring: true
        street: 26 rue de Paris
        postCode: '93100'
        city: Montreuil
        country: FRANCE
        mandateLanguage: es
        rum: '123456'
        signerFirstName: Gael
        signerLastName: Durand
    Card:
      type: object
      properties:
        id:
          format: int64
          description: ''
          type: integer
        is3DS:
          description: Card with 3-DS authentication
          type: boolean
        country:
          description: Card issuing country
          type: string
        authorizationNumber:
          description: Authorization number
          type: string
        maskedNumber:
          description: Masked card number
          type: string
        expiration:
          description: Expiration date (if available)
          type: string
        type:
          description: 'Card type (example: Visa or Mastercard)'
          type: string
        isRegistered:
          description: Card is registered
          type: boolean
        holderName:
          description: Card's holder name
          type: string
    GetMoneyInSddOutput:
      type: object
      properties:
        transactions:
          $ref: '#/components/schemas/Transactions_TransactionIn'
        _links:
          $ref: '#/components/schemas/Links'
        error:
          $ref: '#/components/schemas/Error'
    RegisterSddMandateOutput:
      type: object
      properties:
        SSDMandate:
          $ref: '#/components/schemas/SddMandate'
        error:
          $ref: '#/components/schemas/Error'
    CancelMoneyInInput:
      required:
      - account
      type: object
      properties:
        account:
          description: Payment Account ID
          maxLength: 256
          minLength: 0
          type: string
      example:
        account: Pizza75
    AccountMandatsOutput:
      type: object
      properties:
        mandates:
          description: List of documents that changed since the entry date.
          type: array
          items:
            $ref: '#/components/schemas/SddMandate'
        error:
          $ref: '#/components/schemas/Error'
    Links:
      type: object
      properties:
        first:
          $ref: '#/components/schemas/Link'
        last:
          $ref: '#/components/schemas/Link'
        previous:
          $ref: '#/components/schemas/Link'
        next:
          $ref: '#/components/schemas/Link'
        self:
          $ref: '#/components/schemas/Link'
    MandateGetDocumentOutput:
      description: Output of the MandateGetDocument method
      type: object
      properties:
        document:
          description: Document in base64
          type: string
        name:
          description: Document name
          type: string
        error:
          $ref: '#/components/schemas/Error'
    PSP:
      type: object
      properties:
        message:
          description: Get the Error Message from PSP
          type: string
    MoneyInSddInitInput:
      required:
      - sddMandateId
      - accountId
      type: object
      properties:
        sddMandateId:
          format: int64
          description: Mandate ID
          type: integer
        collectionDate:
          description: 'Debit date of the bank account, must be later than the default date.

            Leave empty in order to use the default date: current date + 1 working days before 10:30 AM or current date + 2 working days after.'
          pattern: ^[12]\d{3}\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])$
          type: string
        reference:
          description: Unique ID of the call, generated by your server. This ID can be used as a search field when looking for operation details
          maxLength: 50
          minLength: 0
          type: string
        accountId:
          description: Payment Account ID to Credit
          maxLength: 256
          minLength: 0
          type: string
        totalAmount:
          format: int32
          description: 'Amount to Debit

            Amounts are given as integer numbers in cents'
          type: integer
        commissionAmount:
          format: int32
          description: 'Your Fee

            Amounts are given as integer numbers in cents'
          type: integer
        comment:
          description: Comment Regarding the Transaction
          maxLength: 140
          minLength: 0
          type: string
        autoCommission:
          description: "If true:\n1. [amountCom] will be ignored and will be replaced with Lemonway's fee  \n2. You will not receive any fee"
          type: boolean
      example:
        sddMandateId: 356
        collectionDate: 2026/08/22
        reference: Dze8778
        accountId: '33612345678'
        totalAmount: 1500
        commissionAmount: 100
        comment: Order number 2457765AX2
        autoCommission: false
    SddMandate:
      type: object
      properties:
        id:
          format: int64
          description: Mandate ID
          type: integer
        status:
          format: int32
          description: Mandate Status<br/>0 = Pending validation.<br/>5 = Validated, First SDD to be done.<br/>6 = Enabled.<br/>8 = Disabled.<br/>9 = Rejected.<br/>
          enum:
          - 0
          - 5
          - 6
          - 8
          - 9
          type: integer
        IBAN:
          description: IBAN associated to the mandate
          type: string
        BIC:
          description: SWIFT code associated to the mandate
          type: string
        holder:
          description: IBAN Holder
          type: string
        UniqueMandateReference:
          description: Unique mandate reference
          type: string
x-provenance:
  method: searched
  source: https://documentation.lemonway.com/reference
  harvested: '2026-10-14'
  tool: harvest-readme-openapi.py
  note: Assembled verbatim from the OpenAPI definition ReadMe embeds in each operation page of the provider's developer portal; paths and components merged by API title, nothing authored.
  assembled_from:
  - https://documentation.lemonway.com/reference/accounts_accountsingleget.md
  - https://documentation.lemonway.com/reference/accounts_addultimatebeneficialowner.md
  - https://documentation.lemonway.com/reference/accounts_balancesget.md
  - https://documentation.lemonway.com/reference/accounts_balanceshistoryget.md
  - https://documentation.lemonway.com/reference/accounts_blockedput.md
  - https://documentation.lemonway.com/reference/accounts_documentget.md
  - https://documentation.lemonway.com/reference/accounts_documentssigninitpost.md
  - https://documentation.lemonway.com/reference/accounts_documentsuploadpost.md
  - https://documentation.lemonway.com/reference/accounts_enrolmentinit.md
  - https://documentation.lemonway.com/reference/accounts_getultimatebeneficialowner.md
  - https://documentation.lemonway.com/reference/accounts_individualpost.md
  - https://documentation.lemonway.com/reference/accounts_individualput.md
  - https://documentation.lemonway.com/reference/accounts_kycstatusget.md
  - https://documentation.lemonway.com/reference/accounts_kycstatusput.md
  - https://documentation.lemonway.com/reference/accounts_legalpost.md
  - https://documentation.lemonway.com/reference/accounts_legalsingleput.md
  - https://documentation.lemonway.com/reference/accounts_retrievepost.md
  - https://documentation.lemonway.com/reference/accounts_transactionsget.md
  - https://documentation.lemonway.com/reference/accounts_updateultimatebeneficialowner.md
  - https://documentation.lemonway.com/reference/disputes_disputesget.md
  - https://documentation.lemonway.com/reference/moneyins_accountcardget.md
  - https://documentation.lemonway.com/reference/moneyins_bankwireget.md
  - https://documentation.lemonway.com/reference/moneyins_bankwireibancountget.md
  - https://documentation.lemonway.com/reference/moneyins_bankwireibancreatepost.md
  - https://documentation.lemonway.com/reference/moneyins_bankwireibandisablepost.md
  - https://documentation.lemonway.com/reference/moneyins_cancelput.md
  - https://documentation.lemonway.com/reference/moneyins_cardcreatepost.md
  - https://documentation.lemonway.com/reference/moneyins_carddirect3dconfirmput.md
  - https://documentation.lemonway.com/reference/moneyins_cardget.md
  - https://documentation.lemonway.com/reference/moneyins_cardpaymentformpost.md
  - https://documentation.lemonway.com/reference/moneyins_cardrebill.md
  - https://documentation.lemonway.com/reference/moneyins_cardsubscriptionpost.md
  - https://documentation.lemonway.com/reference/moneyins_cardunregisterput.md
  - https://documentation.lemonway.com/reference/moneyins_cardwebinitpost.md
  - https://documentation.lemonway.com/reference/moneyins_chequeget.md
  - https://documentation.lemonway.com/reference/moneyins_chequeinitpost.md
  - https://documentation.lemonway.com/reference/moneyins_createbnplpayment.md
  - https://documentation.lemonway.com/reference/moneyins_getbnplpaymentplans.md
  - https://documentation.lemonway.com/reference/moneyins_getmoneyinbanks.md
  - https://documentation.lemonway.com/reference/moneyins_mandateget.md
  - https://documentation.lemonway.com/reference/moneyins_mandategetdocument.md
  - https://documentation.lemonway.com/reference/moneyins_mbwayinitpost.md
  - https://documentation.lemonway.com/reference/moneyins_mobilepayinitpost.md
  - https://documentation.lemonway.com/reference/moneyins_moneyinapminitasync.md
  - https://documentation.lemonway.com/reference/moneyins_moneyinget.md
  - https://documentation.lemonway.com/reference/moneyins_moneyinpaypalinit.md
  - https://documentation.lemonway.com/reference/moneyins_moneyintransferinit.md
  - https://documentation.lemonway.com/reference/moneyins_multibancoinitpost.md
  - https://documentation.lemonway.com/reference/moneyins_paymentformcompletedget.md
  - https://documentation.lemonway.com/reference/moneyins_paymentformdisableput.md
  - https://documentation.lemonway.com/reference/moneyins_paypaltransactionresume.md
  - https://documentation.lemonway.com/reference/moneyins_payshopinitpost.md
  - https://documentation.lemonway.com/reference/moneyins_paytrailinitpost.md
  - https://documentation.lemonway.com/reference/moneyins_sddget.md
  - https://documentation.lemonway.com/reference/moneyins_sddinitpost.md
  - https://documentation.lemonway.com/reference/moneyins_sddmandatepost.md
  - https://documentation.lemonway.com/reference/moneyins_sddmandateunregisterput.md
  - https://documentation.lemonway.com/reference/moneyins_sofortinitpost.md
  - https://documentation.lemonway.com/reference/moneyins_trustlyinitpost.md
  - https://documentation.lemonway.com/reference/moneyins_validateput.md
  - https://documentation.lemonway.com/reference/moneyouts_cancelput.md
  - https://documentation.lemonway.com/reference/moneyouts_ibanextendedpost.md
  - https://documentation.lemonway.com/reference/moneyouts_ibanget.md
  - https://documentation.lemonway.com/reference/moneyouts_ibanpost.md
  - https://documentation.lemonway.com/reference/moneyouts_ibanunregisterput.md
  - https://documentation.lemonway.com/reference/moneyouts_moneyoutget.md
  - https://documentation.lemonway.com/reference/moneyouts_moneyoutpostasync.md
  - https://documentation.lemonway.com/reference/p2ps_p2pget.md
  - https://documentation.lemonway.com/reference/p2ps_p2ppost.md
  - https://documentation.lemonway.com/reference/refunds_refundcreateput.md
  - https://documentation.lemonway.com/reference/refunds_refundput.md
  merge:
    pages: 71
    deduped: 281
    conflicts_kept_first: 0
